spring.application.name=FolderSearch

spring.datasource.url=jdbc:mysql://localhost:3306/eqdom_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.id.new_generator_mappings=false

server.port=8080

storage.location = storage/contracts

#minio
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=contracts

#signature service
signature-service.url=http://localhost:8081

#keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/eqdom